services:
  ssrf_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    networks:
      company_lan:
        ipv4_address: 172.20.0.100

  confidential_service:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "5050"
    command: ["python", "confidential_service.py"]
    networks:
      company_lan:
        ipv4_address: 172.20.0.110

networks:
  company_lan:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24